site_name: Yizhou Shan's Home Page
site_author: 'Yizhou Shan'
site_url: 'http://lastweek.io'

pages:
- Home: 'index.md'
- Notes:
   - 'Cache Coherence':                  'notes/cache_coherence.md'
   - 'Benchmarks':                       'notes/benchmark.md'
   - 'Perf Shadows':                     'notes/paper_perf_shadows.md'
   - 'Linux Articles':                   'notes/linux-articles.md'
   - '[Linux] Special Files':            'notes/proc.md'
   - '[Linux] Reverse Mmap (rmap)':      'notes/rmap.md'
   - '[Linux] Trace/Profile':            'notes/trace.md'
   - '[Linux] Cgroup and Swap':          'notes/cgroup-swap.md'
   - '[Linux] Userfaultfd':              'notes/userfaultfd.md'
   - '[Linux] User/kern Cross Perf':     'notes/xperf.md'
   - '[Linux] KVM':                      'notes/kvm-basic.md'
   - 'Essential':                        'misc/essential.md'
   - 'Cheatsheet':                       'misc/cheatsheet.md'
- FPGA:
   - 'FPGA Papers':                      'notes/paper_fpga.md'
   - 'Vivado Practice':                  'fpga/vivado.md'
   - 'Bitstream Explained':              'fpga/bitstream.md'
   - 'HLS: Usage of AXI-Stream':         'fpga/hls_axi.md'
   - 'HLS: High-performance AXI-MM':     'fpga/hls_axi.md'
- LegoOS-Dev:
   - 'Log':
           - 'TODO':                    'lego/log/TODO.md'
           - 'MISC':                    'lego/log/misc.md'
           - 'Test Script':             'lego/log/test-note.md'
           - 'Sep 2018':                'lego/log/log-09-2018.md'
           - 'Aug 2018':                'lego/log/log-08-2018.md'
           - 'April 2018':              'lego/log/log-04-2018.md'
           - 'March 2018':              'lego/log/log-03-2018.md'
           - 'Feb 2018':                'lego/log/log-02-2018.md'
   - 'Kernel':
        - 'Kconfig': 'lego/kernel/kconfig.md'
        - 'Debug': 'lego/kernel/debug.md'
        - 'GRUB': 'lego/kernel/grub.md'
        - 'Profile': 'lego/kernel/profile.md'
        - 'Profile strace': 'lego/kernel/profile_strace.md'
        - 'Profile heatmap': 'lego/kernel/profile_heatmap.md'
        - 'Profile points': 'lego/kernel/profile_points.md'
        - 'Trampoline': 'lego/kernel/trampoline.md'
        - 'Disable pgfault': 'lego/kernel/pagefault_disable.md'
        - 'Stop machine': 'lego/kernel/stop_machine.md'
        - 'Program Loader': 'lego/kernel/loader.md'
        - 'vDSO': 'lego/kernel/vDSO.md'
        - 'Virtual File System': 'lego/kernel/vfs.md'
        - 'Process Virtual Memory': 'lego/kernel/vm.md'
        - 'x86 FPU': 'lego/kernel/fpu.md'
        - 'IRQ': 'lego/kernel/irq.md'
        - 'Network Thpool': 'lego/kernel/net_thpool.md'
   - Syscall:
           - 'Facts':         'lego/syscall/facts.md'
           - 'strace': 'lego/kernel/profile_strace.md'
           - 'compat':        'lego/syscall/compat.md'
           - 'msync()':       'lego/syscall/msync.md'
           - 'mremap()':      'lego/syscall/mremap.md'
           - 'fork()':        'lego/syscall/fork.md'
           - 'getrusage()':   'lego/syscall/getrusage.md'
           - 'wait4 and exit()': 'lego/syscall/wait_and_exit.md'
   - Pcache:
           - 'Config': 'lego/pcache/config.md'
           - 'Sweep': 'lego/pcache/sweep.md'
           - 'TLB Coherence': 'lego/pcache/tlb.md'
           - 'PageTable Lock': lego/pcache/pgtable-lock.md
           - 'Victim Cache': 'lego/pcache/victim.md'
           - 'Virtual Cache': 'lego/pcache/virtual_cache.md'
           - 'Reverse Mapping': 'lego/pcache/rmap.md'
           - 'Evict and Refcount': 'lego/pcache/evict_and_ref.md'
           - 'SMP Design': 'lego/pcache/smp_design.md'
           - 'Replication': 'lego/pcache/replication.md'
   - Driver:
           - 'PCI': 'lego/driver/pci.md'
           - 'Infiniband': 'lego/driver/ib.md'
   - Paper:
           - 'NMP': 'lego/paper/nmp.md'
           - 'Processor OOM': 'lego/paper/processor_oom.md'
           - 'Gen-Z': 'lego/paper/genz.md'
           - 'Replication': 'lego/paper/replication.md'
           - 'Related': 'lego/paper/related.md'

markdown_extensions:
  - admonition
  - tables
  - smarty
  - footnotes
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.progressbar

theme:
  name: 'rtd-dropdown'
  #name: 'material'
  palette:
    #primary: 'Teal'
    #accent: 'Green'
  font:
    #text: 'Times New Roman'
    code: 'Courier'

google_analytics:
  - 'UA-143772066-1'
  - 'auto'

# Options
extra:
  #logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/lastweek'
  disqus: 'lastweek-io'
