site_name: Yizhou Shan's Home Page
pages:
- Home: index.md
- Jasmine: 'misc/jasmine.md'
- Cheatsheet: 'misc/cheatsheet.md'
- Essentials: 'misc/essential.md'
- Read:
   - 'FAST 18': 'read/fast18.md'
   - 'ASPLOS 18': 'read/asplos18.md'
- Lego:
   - 'Log':
           - 'TODO': 'lego/log/TODO.md'
           - 'MISC': 'lego/log/misc.md'
           - 'April 2018':           'lego/log/log-04-2018.md'
           - 'March 2018':           'lego/log/log-03-2018.md'
           - 'Feb 2018':           'lego/log/log-02-2018.md'
   - 'Kernel':
        - 'Kconfig': 'lego/kernel/kconfig.md'
        - 'Debug': 'lego/kernel/debug.md'
        - 'GRUB': 'lego/kernel/grub.md'
        - 'Profile': 'lego/kernel/profile.md'
        - 'Profile strace': 'lego/kernel/profile_strace.md'
        - 'Profile heatmap': 'lego/kernel/profile_heatmap.md'
        - 'Profile points': 'lego/kernel/profile_points.md'
        - 'Trampoline': 'lego/kernel/trampoline.md'
        - 'Disable pgfault': 'lego/kernel/pagefault_disable.md'
        - 'Stop machine': 'lego/kernel/stop_machine.md'
        - 'Program Loader': 'lego/kernel/loader.md'
        - 'vDSO': 'lego/kernel/vDSO.md'
        - 'Virtual File System': 'lego/kernel/vfs.md'
        - 'Process Virtual Memory': 'lego/kernel/vm.md'
        - 'x86 FPU': 'lego/kernel/fpu.md'
   - Syscall:
           - 'Facts':         'lego/syscall/facts.md'
           - 'strace': 'lego/kernel/profile_strace.md'
           - 'compat':        'lego/syscall/compat.md'
           - 'msync()':       'lego/syscall/msync.md'
           - 'mremap()':      'lego/syscall/mremap.md'
           - 'fork()':        'lego/syscall/fork.md'
           - 'getrusage()':   'lego/syscall/getrusage.md'
           - 'wait4 and exit()': 'lego/syscall/wait_and_exit.md'
   - Pcache:
           - 'Config': 'lego/pcache/config.md'
           - 'Sweep': 'lego/pcache/sweep.md'
           - 'TLB Coherence': 'lego/pcache/tlb.md'
           - 'PageTable Lock': lego/pcache/pgtable-lock.md
           - 'Victim Cache': 'lego/pcache/victim.md'
           - 'Virtual Cache': 'lego/pcache/virtual_cache.md'
           - 'Reverse Mapping': 'lego/pcache/rmap.md'
           - 'Evict and Refcount': 'lego/pcache/evict_and_ref.md'
           - 'SMP Design': 'lego/pcache/smp_design.md'
           - 'Replication': 'lego/pcache/replication.md'
   - Paper:
           - 'NMP': 'lego/paper/nmp.md'
           - 'Processor OOM': 'lego/paper/processor_oom.md'
           - 'Gen-Z': 'lego/paper/genz.md'
           - 'Replication': 'lego/paper/replication.md'
           - 'Related': 'lego/paper/related.md'

markdown_extensions:
  - tables
  - smarty
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.progressbar
  - codehilite:
      linenums: true
      guess_lang: true

theme:
  name: 'material'
