site_name: Yizhou Shan's Home Page
site_author: 'Yizhou Shan'
site_url: 'http://lastweek.io'

nav:
- Home: 'index.md'
- Code Landscape:
   - 'All':                         'notes/source_code/summary.md'
   - 'Graphics':                    'notes/source_code/20200501-on-graphic-softwares.md'
   - 'Firmware':                    'notes/source_code/20200506-on-firmware-softwares.md'
   - 'RDMA/DPDK':                   'notes/source_code/rdma.md'
   - 'Virtualization':              'notes/source_code/virt.md'
   - 'Guideline & Advice':          'notes/program_advice.md'

- Notes:
   - 'Practical-Cache-Coherence':                       'notes/cache_coherence.md'
   - 'x86-Ring-Switch-Overhead':                'notes/xperf.md'
   - 'Performance-Shadows':                             'notes/paper_perf_shadows.md'
   - 'Linux Reverse Map (rmap)':       'notes/rmap.md'
   - 'Linux Userfaultfd':              'notes/userfaultfd.md'
   - 'Linux Trace/Profile':            'notes/trace.md'
   - 'Linux Cgroup and Swap':          'notes/cgroup-swap.md'
   - 'Linux Special Files':            'notes/proc.md'
   - 'Linux Resource':                 'notes/linux-resource.md'
   - 'Linux KVM':                      'notes/kvm-basic.md'
   - 'Essential':                        'misc/essential.md'
   - 'Benchmarks':                       'notes/benchmark.md'
   - 'Cheatsheet':                       'misc/cheatsheet.md'
- Random:
   - '2020-04 On-Read-Once-and-Compiler-Opts':    'blog/20200404-on-read-once.md'
   - '2020-04 On-Hardware-based-Network-Transport': 'blog/20200404-on-net-transport.md'
- FPGA:
   - 'Papers':                                          'notes/paper_fpga.md'
   - 'Languages'                                        'fpga/language.md'
   - 'Bitstream Explained':                             'fpga/bitstream.md'
   - 'Morphous Partial Reconfiguration':                     'fpga/pr.md'
   - 'Vivado Notes':                                     'fpga/vivado.md'
   - 'Efficient AXI-MM':                                 'fpga/hls_axi.md'
- LegoOS:
#   - 'Log':
#           - 'TODO':                    'lego/log/TODO.md'
#           - 'MISC':                    'lego/log/misc.md'
#           - 'Test Script':             'lego/log/test-note.md'
#           - 'Sep 2018':                'lego/log/log-09-2018.md'
#           - 'Aug 2018':                'lego/log/log-08-2018.md'
#           - 'April 2018':              'lego/log/log-04-2018.md'
#           - 'March 2018':              'lego/log/log-03-2018.md'
#           - 'Feb 2018':                'lego/log/log-02-2018.md'
   - 'Kernel':
        - 'GRUB2 and Boot' : 'lego/kernel/boot.md'
        - 'Kconfig': 'lego/kernel/kconfig.md'
        - 'Debug': 'lego/kernel/debug.md'
        - 'GRUB': 'lego/kernel/grub.md'
        - 'Profile': 'lego/kernel/profile.md'
        - 'Profile strace': 'lego/kernel/profile_strace.md'
        - 'Profile heatmap': 'lego/kernel/profile_heatmap.md'
        - 'Profile points': 'lego/kernel/profile_points.md'
        - 'Trampoline': 'lego/kernel/trampoline.md'
        - 'Disable pgfault': 'lego/kernel/pagefault_disable.md'
        - 'Stop machine': 'lego/kernel/stop_machine.md'
        - 'Program Loader': 'lego/kernel/loader.md'
        - 'vDSO': 'lego/kernel/vDSO.md'
        - 'Virtual File System': 'lego/kernel/vfs.md'
        - 'Process Virtual Memory': 'lego/kernel/vm.md'
        - 'x86 FPU': 'lego/kernel/fpu.md'
        - 'IRQ': 'lego/kernel/irq.md'
        - 'Network Thpool': 'lego/kernel/net_thpool.md'
   - Syscall:
           - 'Facts':         'lego/syscall/facts.md'
           - 'strace': 'lego/kernel/profile_strace.md'
           - 'compat':        'lego/syscall/compat.md'
           - 'msync()':       'lego/syscall/msync.md'
           - 'mremap()':      'lego/syscall/mremap.md'
           - 'fork()':        'lego/syscall/fork.md'
           - 'getrusage()':   'lego/syscall/getrusage.md'
           - 'wait4 and exit()': 'lego/syscall/wait_and_exit.md'
   - Pcache:
           - 'Config': 'lego/pcache/config.md'
           - 'Sweep': 'lego/pcache/sweep.md'
           - 'TLB Coherence': 'lego/pcache/tlb.md'
           - 'PageTable Lock': 'lego/pcache/pgtable-lock.md'
           - 'Victim Cache': 'lego/pcache/victim.md'
           - 'Virtual Cache': 'lego/pcache/virtual_cache.md'
           - 'Reverse Mapping': 'lego/pcache/rmap.md'
           - 'Evict and Refcount': 'lego/pcache/evict_and_ref.md'
           - 'SMP Design': 'lego/pcache/smp_design.md'
           - 'Replication': 'lego/pcache/replication.md'
   - Driver:
           - 'PCI': 'lego/driver/pci.md'
           - 'Infiniband': 'lego/driver/ib.md'
   - Paper:
           - 'NMP': 'lego/paper/nmp.md'
           - 'Processor OOM': 'lego/paper/processor_oom.md'
           - 'Gen-Z': 'lego/paper/genz.md'
           - 'Replication': 'lego/paper/replication.md'
           - 'Related': 'lego/paper/related.md'
markdown_extensions:
  - admonition
  - tables
  - smarty
  - footnotes
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.progressbar

plugins:
  - search
  - git-revision-date-localized

#name: 'material'
#name: 'rtd-dropdown'
#name: 'gitbook'
#name: 'readthedocs'
theme:
  name: 'material'
  font:
    #text: 'Montserrat'
    #text: 'Open Sans'
  icon:
    logo: material/cloud
    repo: fontawesome/brands/git-alt
  features:
          #- tabs
    - instant
  palette:
          #scheme: slate

google_analytics:
  - 'UA-143772066-1'
  - 'auto'

# Options
extra:
  logo: "images/logo.svg"
  #  social:
  #  - type: 'github'
  #    link: 'https://github.com/lastweek'
  #  - type: 'twitter'
  #    link: 'https://twitter.com/Yizhou_Shan'
  #  - type: 'linkedin'
  #    link: 'https://www.linkedin.com/in/lastweek/'
  disqus: 'lastweek-io'
